name: 'Obrigado'
description: 'Agradece a pull request e cria um card no trello'
author: 'Rodrigo Jose'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  TENOR_TOKEN:
    description: 'Tenor API token'
    required: true
  TRELLO_KEY:
    description: 'trello API key'
    required: true
  TRELLO_TOKEN:
    description: 'trello API token'
    required: true
  TRELLO_IDLIST:
    description: 'trello id lista card'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'