name: Test

on:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TENOR_TOKEN: ${{secrets.TENOR_TOKEN}}
          TRELLO_KEY: ${{secrets.TRELLO_KEY}}
          TRELLO_TOKEN: ${{secrets.TRELLO_TOKEN}}
          TRELLO_IDLIST: ${{secrets.TRELLO_IDLIST}}